---
title: "Execicio 3"
output: html_notebook
---


```{r}
# CARREGAR O PACOTE
library(data.table)
# LEITURA DA BASE
base =
  fread(
    input = paste0("mobile.csv"),
    header = T,
    na.strings = "NA",
    data.table = FALSE,
    dec = "."
  )

# FORMATACAO
library(dplyr)
base$touch_screen = recode(base$touch_screen,
                           `0` = "0:Não tem",
                           `1` = "1:Tem", )

library(dplyr)
base$blue = recode(base$blue,
                   `0` = "0:Não tem",
                   `1` = "1:Tem", )


write.csv2(base, "base.csv", row.names = FALSE)
```


```{r}
# AMOSTRA SIMPLES AO ACASO
asa600 = base[sample(nrow(base), size = 600),]
```



```{r}
# DATAFRAME POTENCIA DA BATERIA E TOUCH SCREEN
df = data.frame(asa600$touch_screen, asa600$battery_power)

# TABELA MEDIA, DESVIO PADRAO E COEFICIENTE DE VARIABILIDADE
battery_table = aggregate(
  asa600$battery_power ~ asa600$touch_screen,
  data = asa600,
  FUN = function(x) {
    c(mean = mean(x),
      sd = sd(x),
      cv = sd(x) / mean(x) * 100)
  }
)

# FORMATAR COLUNAS
colnames(battery_table)[1] = "touch_screen"
colnames(battery_table)[2] = "battery_pw_summary"

# TIRAR DA MATRIZ
matriz_battery_pw = battery_table$battery_pw_summary[, 1:3]
battery_table = cbind(battery_table[, 1:2], as.data.frame(matriz_battery_pw))
battery_table = data.frame(battery_table[0:1], battery_table[3:5])

# FORMATAR COLUNAS
colnames(battery_table)[0:4] = c("touch_screen",
                                 "battery_pw_mean",
                                 "battery_pw_sd",
                                 "battery_pw_cv")
```


```{r}
# DATAFRAME PROFUNDIDADE E TOUCH SCREEN
df = data.frame(asa600$touch_screen, asa600$m_dep)

# TABELA MEDIA, DESVIO PADRAO E COEFICIENTE DE VARIABILIDADE
m_dep_table = aggregate(
  asa600$m_dep ~ asa600$touch_screen,
  data = asa600,
  FUN = function(x) {
    c(mean = mean(x),
      sd = sd(x),
      cv = sd(x) / mean(x) * 100)
  }
)

# FORMATAR COLUNAS
colnames(m_dep_table)[1] = "touch_screen"
colnames(m_dep_table)[2] = "m_dep_summary"

# TIRAR DA MATRIZ
matriz_m_dep = m_dep_table$m_dep_summary[, 1:3]
m_dep_table = cbind(m_dep_table[, 1:2], as.data.frame(matriz_m_dep))
m_dep_table = data.frame(m_dep_table[0:1], m_dep_table[3:5])

# FORMATAR COLUNAS
colnames(m_dep_table)[0:4] = c("touch_screen",
                               "m_dep_mean",
                               "m_dep_sd",
                               "m_dep_cv") 
```


```{r}
# DATAFRAME MEMORIA INTERNA E BLUETOOTH
df = data.frame(asa600$blue, asa600$int_memory)

# TABELA MEDIA, DESVIO PADRAO E COEFICIENTE DE VARIABILIDADE
int_memory_table = aggregate(
  asa600$int_memory ~ asa600$blue,
  data = asa600,
  FUN = function(x) {
    c(mean = mean(x),
      sd = sd(x),
      cv = sd(x) / mean(x) * 100)
  }
)

# FORMATAR COLUNAS
colnames(int_memory_table)[1] = "blue"
colnames(int_memory_table)[2] = "int_memory_summary"

# TIRAR DA MATRIZ
matriz_int_memory = int_memory_table$int_memory_summary[, 1:3]
int_memory_table = cbind(int_memory_table[, 1:2], as.data.frame(matriz_int_memory))
int_memory_table = data.frame(int_memory_table[0:1], int_memory_table[3:5])

# FORMATAR COLUNAS
colnames(int_memory_table)[0:4] = c("blue",
                                    "int_memory_mean",
                                    "int_memory_sd",
                                    "int_memory_cv")
```


```{r}
# BOXPLOT POTENCIA DA BATERIA POR TOUCH SCREEN
boxplot(
  asa600$battery_power ~ asa600$touch_screen,
  data = asa600,
  main = "Comparação da Potência da Bateria com ter ou não Touch Screen",
  xlab = "Touch Screen",
  ylab = "Potência da Bateria(mAh)",
  col = c("lightcoral", "lightblue")
)
```


```{r}
# BOXPLOT PROFUNDIDADE POR TOUCH SCREEN
boxplot(
  asa600$m_dep ~ asa600$touch_screen,
  data = asa600,
  main = "Comparação da Profundidade com ter ou não Touch Screen",
  xlab = "Touch Screen",
  ylab = "Profundidade(cm)",
  col = c("lightcoral", "lightblue")
)
```


```{r}
# BOXPLOT MEMORIA INTERNA POR BLUETOOTH
boxplot(
  asa600$int_memory ~ asa600$blue,
  data = asa600,
  main = "Comparação da Memória Interna com ter ou não Bluetooth",
  xlab = "Bluetooth",
  ylab = "Memória Interna (GB)",
  col = c("lightcoral", "lightblue")
)
```

